"""add teams

Revision ID: 2662618f5b42
Revises: 968b436216c4
Create Date: 2026-06-02 17:07:22.661744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2662618f5b42'
down_revision: Union[str, None] = '968b436216c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
