"""create todos table

Revision ID: 3ee2cef5c015
Revises: ab10ea26129e
Create Date: 2026-05-30 19:12:13.311081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ee2cef5c015'
down_revision: Union[str, None] = 'ab10ea26129e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
