"""create todos table

Revision ID: 77c994d7ed9e
Revises: 3ee2cef5c015
Create Date: 2026-05-30 19:26:44.638667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77c994d7ed9e'
down_revision: Union[str, None] = '3ee2cef5c015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
