"""create items table

Revision ID: ab10ea26129e
Revises: 1cd75220ce8a
Create Date: 2026-05-30 19:11:30.840618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab10ea26129e'
down_revision: Union[str, None] = '1cd75220ce8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
